default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miniirawo_development
  username: irawo
  password: irawopassword

test:
  <<: *default
  database: miniirawo_test
  username: irawo
  password: irawopassword

production:
  primary: &primary_production
    <<: *default
    database: miniirawo_production
    username: irawo
    password: <%= ENV["MINIIRAWO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: miniirawo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: miniirawo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: miniirawo_production_cable
    migrations_paths: db/cable_migrate
